### ISSUE TITLE
version 0.1.4 doesn't have updated Brazil timezone information

### ISSUE THREAD

**Issue by RostyslavSh** [prantlf/date-fns-timezone#17]
This year Brazil is no longer observing daylight saving time. The library still applies -2 offset in the winter time. Tested with 'America/Sao_Paulo' timezone.

**Comment by jovrtn** [comment]
Looks like the dependency [prantlf/timezone-support](https://github.com/prantlf/timezone-support) hasn't been updated in 7 months and is missing the last two [IANA timezone database](https://www.iana.org/time-zones) updates (2019b and 2019c). Might be better to create an issue there.
