### ISSUE TITLE
IE error occured

### ISSUE THREAD

**Issue by AndriiDidkivsky** [prantlf/date-fns-timezone#2]
Hi.
I've got an error in IE "Expected identifier". As I understood it caused bacause [timezone-support](https://github.com/prantlf/timezone-support) is into ES5. Because in debug mode i see 
`function c({year:n,month:e,day:l,hours:t,minutes:o,seconds:i=0,milliseconds:u=0}){return Date.UTC(n,e-1,l,t,o,i,u)}`. 

Could you check please ?

**Comment by prantlf** [comment]
Yes, it appears to be caused by the lack of testing on IE, like the [similar issue in `timezone-support`](https://github.com/prantlf/timezone-support/issues/3).

**Comment by AndriiDidkivsky** [comment]
timezone-support resolved, but if I install date-fns-timezone package then 1.5.4 dep installed. 
there is only way to resolve - obviously install 1.5.5 in the project. 
Check please

**Comment by AndriiDidkivsky** [comment]
it was npm cache :(

**Comment by prantlf** [comment]
So it was the `timezone-support`! I checked, that the output cjs modules have been babelified already. I upgraded the `timezone-support` to 1.5.5 and released it as [0.1.4](https://github.com/prantlf/date-fns-timezone/releases/tag/v0.1.4). You shouldn't need to override the module version any more.

Thank you!
